### ISSUE TITLE
Automation Actions displays Error.

### ISSUE THREAD

**Issue by TheOrdinaryWow** [darthShadow/docker-whmcs#2]
`Automation Actions` displays error, `Daily Cron Run Status` and `Daily Cron Completing` is -, though cron has been configured inside docker container:
```
crontab -e
> Add line: */1 * * * * /usr/bin/php -q /config/www/whmcs/crons/cron.php
> save file
```

**Comment by darthShadow** [comment]
You can take a look at the default crons @ https://github.com/darthShadow/docker-whmcs/blob/f6adb3b1af678b386ae16bec663fbafb8b8b2c12/root/defaults/cron/whmcs to see how to add a custom cronjob.


Basically, it needs to be run via the abc user, so something like this should work:

```
*/1 * * * * s6-setuidgid abc php -q /config/www/whmcs/crons/cron.php
```
